"""Guard the auto-generated code blocks against undetected drift.

``test_automethods.py`` guards the *names* on the generated expression surface.
Nothing there guards the generated *content*: hand-edit a block between the
``# Begin auto-generated code`` / ``# End auto-generated code`` markers, or edit
the name sets in ``automethods._main`` without rerunning the generator, and the
on-disk blocks go stale while CI stays green.

``scripts/autogenerate.py --check`` closes that gap. It regenerates every
generated file into a scratch tree and compares each against the file on disk,
exiting nonzero (and naming the drifted files) on any mismatch. The comparison is
on parsed syntax, so the check needs no formatter and runs everywhere rather than
skipping in every job that lacks one.

Scope, since the two guards are easy to confuse. The generator emits from the
literal name sets in ``automethods._main``, not by introspecting the classes, so
adding a method to Matrix/Vector/Scalar does not change its output and cannot
show up here. That case is ``test_automethods.py``'s: it compares the concrete
types against the generated surface and fails when a new public attribute is
neither auto-computed nor opted out. This module covers the other half, the
generated files no longer matching the generator that claims to produce them.
"""

import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
AUTOGEN_SCRIPT = REPO_ROOT / "scripts" / "autogenerate.py"
PACKAGE_LINE = "graphblas package: "


def test_autogenerated_code_is_in_sync():
    if not AUTOGEN_SCRIPT.exists():  # pragma: no cover (source checkout only)
        pytest.skip("scripts/autogenerate.py not present (installed package, not a checkout)")
    result = subprocess.run(
        [sys.executable, str(AUTOGEN_SCRIPT), "--check"],
        capture_output=True,
        text=True,
        check=False,
    )
    report = f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}"
    checked = [
        line[len(PACKAGE_LINE) :].strip()
        for line in result.stdout.splitlines()
        if line.startswith(PACKAGE_LINE)
    ]

    # Assert the positive post-condition before the exit code. A check that ran against a
    # different `graphblas` reports success about a tree nobody asked about: sys.path[0]
    # for a script is the script's own directory, so that is what happens whenever an
    # editable install points elsewhere, as in a git worktree.
    assert checked, f"--check never reported a package, so it failed before starting.\n{report}"
    expected = str(REPO_ROOT / "graphblas")
    assert checked == [expected], f"--check validated {checked}, not {expected}.\n{report}"

    assert result.returncode == 0, (
        "Auto-generated code is out of date. Run `python scripts/autogenerate.py` and "
        f"commit the result.\n{report}"
    )
